[package]
name = "goxidize"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A link shortener"
repository = "https://github.com/caizixian/goxidize"
homepage = "https://github.com/caizixian/goxidize"
readme = "README.md"
documentation = "https://docs.rs/goxidize"
categories = ["web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "goxidize"

[dependencies]
actix-web = "4.0"
actix-files = "0.6"
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "postgres", "uuid", "chrono", "offline"] }
config = { version = "0.13", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = { version = "0.1", features = ["log"] }
tracing-opentelemetry = "0.17"
tracing-actix-web = { version = "0.5", features = ["opentelemetry_0_17"] }
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-log = "0.1"
lazy_static = "1.4"
opentelemetry = { version = "0.17", features = ["rt-tokio-current-thread"] }
opentelemetry-otlp = "0.10"
tokio = { version = "1.17", features = ["macros", "sync", "rt"] }

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
