[package]
name = "goxidize"
version = "0.1.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "goxidize"

[dependencies]
actix-web = "4.0.0-beta.10"
actix-files = "0.6.0-beta.8"
sqlx = { version = "0.5", features = ["runtime-actix-rustls", "postgres", "uuid", "chrono", "offline"] }
config = { version = "0.11", default-features = false, features = ["yaml"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "0.8", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.9"
log = "0.4"
tracing = { version = "0.1", features = ["log"] }
tracing-opentelemetry = "0.16"
tracing-actix-web = { version = "0.5.0-beta.1", features = ["opentelemetry_0_16"] }

[dev-dependencies]
tokio = { version = "1.13", features = ["macros", "sync", "rt"] }
reqwest = { version = "0.11", features = ["json"] }
actix-rt = "2.3"
